spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/mercadolivro?createDatabaseIfNotExist=true
    username: root
    password: 34097166
  flyway:
    url: jdbc:mysql://localhost:3306/mysql
    schemas: USERSERVICE
    user: "root"
    password: "34097166"
  jackson:
    default-property-inclusion: non_null
